version: '3'
services:
  taxon-pg:
    image: postgres:14.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "abcdefgh"
  taxon-web:
    depends_on:
      - taxon-pg
    image: tomcat:9.0.38
    volumes:
      - ./target/taxon.war:/usr/local/tomcat/webapps/taxon.war
    ports:
      - 8081:8080


