version: '3'
services:
  taxon-pg:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "abcdefgh"
  taxon-web:
    depends_on:
      - taxon-pg
    image: tomcat:9.0.38
    ports:
      - '8082:8080'


